### ISSUE TITLE
[Cloud Foundry] experiment "Unbind_service_from_app" doesn't work

### ISSUE THREAD

**Issue by ChakirGit** [chaostoolkit/chaostoolkit#262]
Hello everyone,

I tried to run an experiment on cloudfoundry environment (unbind service from app) but when i run the json file, i get an error

```
[2022-05-02 15:33:18 INFO] Validating the experiment's syntax
[2022-05-02 15:33:19 INFO] Experiment looks valid
[2022-05-02 15:33:19 INFO] Running experiment: unbind d'un service 
[2022-05-02 15:33:19 INFO] Steady-state strategy: default
[2022-05-02 15:33:19 INFO] Rollbacks strategy: default
[2022-05-02 15:33:19 INFO] No steady state hypothesis defined. That's ok, just exploring.
[2022-05-02 15:33:19 INFO] Playing your experiment's method now...
[2022-05-02 15:33:19 INFO] Action: unbind_service_from_app
[2022-05-02 15:33:19 ERROR]      => failed: StopIteration
[2022-05-02 15:33:26 INFO] Let's rollback...
[2022-05-02 15:33:26 INFO] No declared rollbacks, let's move on.
[2022-05-02 15:33:26 INFO] Experiment ended with status: completed
```

I would like to unbind service "rabbitmq" from my app "hello-spring-cloud". So that what i refer in my experiment file:

here is my service "rabbitmq" :

```
~$ cf services
Getting services in org POV / space appchaos as chaos...

name          service       plan                  bound apps           last operation     broker        upgrade available
mon-service   appdynamics   dynam-vipa-01ri67ba   hello-spring-cloud   update succeeded   appdservice   
rabbitmq      p-rabbitmq    standard              hello-spring-cloud   create succeeded   p-rabbitmq 
```
Here is extract from my experiment file:

```
"method": [
        {
            "type": "action",
            "name": "unbind_service_from_app",
            "provider": {
                "type": "python",
                "secrets": ["cloudfoundry"],
                "module": "chaoscf.actions",
                "func": "unbind_service_from_app",
                "arguments": {
                    "app_name": "hello-spring-cloud",
                    "bind_name": "rabbitmq",
                    "org_name": "POV",
                    "space_name": "appchaos"
                }
            }
        }
    ]
}
```

You can also find log from chaostoolkit.log:

```
[36m[2022-03-01 16:00:04 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-03-01 16:00:04 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-03-01 16:00:04 DEBUG] [cli:117][39m Using settings file '/home/icel6280/.chaostoolkit/settings.yaml'
[36m[2022-03-01 16:00:05 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/icel6280/.chaostoolkit/settings.yaml'.
[36m[2022-03-01 16:00:05 DEBUG] [_init_:389][39m No controls to apply on 'loader'
[36m[2022-03-01 16:00:05 DEBUG] [_init_:389][39m No controls to apply on 'loader'
[36m[2022-03-01 16:00:05 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-03-01 16:00:05 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-03-01 16:00:05 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-03-01 16:00:05 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-03-01 16:00:05 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-03-01 16:00:05 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-03-01 16:00:05 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-03-01 16:00:05 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-03-01 16:00:05 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-03-01 16:00:05 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-03-01 16:00:05 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-03-01 16:00:05 DEBUG] [caching:35][39m Cached 1 activities
[36m[2022-03-01 16:00:05 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-03-01 16:00:05 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-03-01 16:00:05 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-03-01 16:00:05 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-03-01 16:00:05 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-03-01 16:00:05 DEBUG] [configuration:155][39m Loading dynamic configuration...
[32m[2022-03-01 16:00:05 INFO] [run:320][39m Running experiment: unbind d'un service
[36m[2022-03-01 16:00:05 DEBUG] [_init_:49][39m Initializing controls
[32m[2022-03-01 16:00:05 INFO] [run:337][39m Steady-state strategy: default
[32m[2022-03-01 16:00:05 INFO] [run:341][39m Rollbacks strategy: default
[32m[2022-03-01 16:00:05 INFO] [run:346][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-03-01 16:00:05 DEBUG] [_init_:389][39m No controls to apply on 'experiment'
[32m[2022-03-01 16:00:05 INFO] [run:600][39m Playing your experiment's method now...
[36m[2022-03-01 16:00:05 DEBUG] [_init_:389][39m No controls to apply on 'method'
[36m[2022-03-01 16:00:05 DEBUG] [_init_:389][39m No controls to apply on 'activity'
[32m[2022-03-01 16:00:05 INFO] [activity:188][39m Action: unbind_service_from_app
[36m[2022-03-01 16:00:05 DEBUG] [python:33][39m Activity 'unbind_service_from_app' loaded from '/home/icel6280/.local/lib/python3.8/site-packages/chaoscf/actions.py'
[36m[2022-03-01 16:00:05 DEBUG] [_init_:54][39m Querying a new access token for client 'cf'
[36m[2022-03-01 16:00:05 DEBUG] [api:47][39m Request ID: 820283f9-3aa3-49da-4d69-638d36de2d52::a75296eb-8243-474c-986a-c393c4a44660
[36m[2022-03-01 16:00:05 DEBUG] [_init_:54][39m Querying a new access token for client 'cf'
[36m[2022-03-01 16:00:06 DEBUG] [api:47][39m Request ID: f5ad27bb-b863-4e9d-4edd-bb0bfbea9c7b::83a30c11-ec73-4da0-bfe5-097e086b535a
[36m[2022-03-01 16:00:06 DEBUG] [_init_:54][39m Querying a new access token for client 'cf'
[36m[2022-03-01 16:00:07 DEBUG] [api:47][39m Request ID: 3180615c-873a-4b9e-57a9-458bdceda250::16fd7db5-2bb5-4a0e-871b-b2f93e08d39f
[36m[2022-03-01 16:00:07 DEBUG] [_init_:54][39m Querying a new access token for client 'cf'
[36m[2022-03-01 16:00:07 DEBUG] [api:47][39m Request ID: 4f3300a0-7f69-45c9-5b8f-922ccc6396de::2c84526a-9d20-40a6-9495-2c0d5997a79f
[36m[2022-03-01 16:00:07 DEBUG] [_init_:54][39m Querying a new access token for client 'cf'
[36m[2022-03-01 16:00:08 DEBUG] [api:47][39m Request ID: 0b807152-0747-4987-50eb-5089890b2ec1::dce53f92-30b3-40a0-a03e-84fb8e1bb344
[36m[2022-03-01 16:00:08 DEBUG] [activity:260][39m Activity failed
    Traceback (most recent call last):
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoscf/actions.py", line 231, in unbind_service_from_app
        service_bind = get_bind_by_name(
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoscf/api.py", line 255, in get_bind_by_name
        service_binding = next(item for item in binds["resources"]
    StopIteration
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 253, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoscf/actions.py", line 231, in unbind_service_from_app
        service_bind = get_bind_by_name(
      File "/home/icel6280/.local/lib/python3.8/site-packages/chaoscf/api.py", line 255, in get_bind_by_name
        service_binding = next(item for item in binds["resources"]
    chaoslib.exceptions.ActivityFailed: StopIteration
[31m[2022-03-01 16:00:08 ERROR] [activity:213][39m   => failed: StopIteration
[36m[2022-03-01 16:00:08 DEBUG] [_init_:389][39m No controls to apply on 'activity'
[36m[2022-03-01 16:00:08 DEBUG] [_init_:389][39m No controls to apply on 'method'
[32m[2022-03-01 16:00:08 INFO] [run:886][39m Let's rollback...
[36m[2022-03-01 16:00:08 DEBUG] [_init_:389][39m No controls to apply on 'rollback'
[32m[2022-03-01 16:00:08 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-03-01 16:00:08 DEBUG] [_init_:389][39m No controls to apply on 'rollback'
[32m[2022-03-01 16:00:08 INFO] [run:451][39m Experiment ended with status: completed
[36m[2022-03-01 16:00:08 DEBUG] [_init_:389][39m No controls to apply on 'experiment'
[36m[2022-03-01 16:00:08 DEBUG] [_init_:82][39m Cleaning up controls
[36m[2022-03-01 16:00:08 DEBUG] [caching:42][39m Clearing activities cache
```

**Runtime versions**

```

:~$ python3 --version
Python 3.8.10


:~$ chaos info core
NAME                VERSION   
CLI                 1.12.0    
Core library        1.25.0


:~$ chaos info extensions
NAME                                    VERSION   LICENSE                       DESCRIPTION                                       
chaostoolkit-cloud-foundry              0.7.1     Apache License Version 2.0    Cloud Foundry    


```
**To Reproduce**

`~$ chaos run unbind_service_from_app.json`

**Expected behavior**

I expected that my experiment file could unbind my rabbitmq service from my app.

If someone has an idea it would be helpful !
Thank you

**Comment by ChakirGit** [comment]
Hi there,
I finally resolved my issue. Actually when i created a binding to the app, i missed an argument which consisting to give a name to this bind "cf bind-service APP_NAME SERVICE_INSTANCE [-c PARAMETERS_AS_JSON] [--binding-name BINDING_NAME]"
that's why my unbind_service experiment didn't work :)
