### ISSUE TITLE
Using Kubernetes context 'default' from config '/home/interns_chaos/.kube/config'

### ISSUE THREAD

**Issue by srimanth-h** [chaostoolkit/chaostoolkit#265]
Using Kubernetes context 'default' from config '/home/interns_chaos/.kube/config'

[2022-06-10 13:09:59 DEBUG] [probes:295] Found 0 failed and 0 not ready pods

[2022-06-10 13:09:59 DEBUG] [activity:205]   => succeeded with 'True'

[2022-06-10 13:09:59 DEBUG] [__init__:399] No controls to apply on 'activity'

[2022-06-10 13:09:59 DEBUG] [hypothesis:221] allowed tolerance is True

[2022-06-10 13:09:59 INFO] [hypothesis:231] Steady state hypothesis is met!

[2022-06-10 13:09:59 DEBUG] [__init__:399] No controls to apply on 'hypothesis'

[2022-06-10 13:09:59 INFO] [run:607] Playing your experiment's method now...

[2022-06-10 13:09:59 DEBUG] [__init__:399] No controls to apply on 'method'

[2022-06-10 13:09:59 DEBUG] [__init__:399] No controls to apply on 'activity'

[2022-06-10 13:09:59 INFO] [activity:188] Action: drain-node

[2022-06-10 13:09:59 DEBUG] [python:33] Activity 'drain-node' loaded from '/home/interns_chaos/.local/lib/python3.8/site-packages/chaosk8s/node/actions.py'

[2022-06-10 13:09:59 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/home/interns_chaos/.kube/config'

[2022-06-10 13:09:59 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/home/interns_chaos/.kube/config'

[2022-06-10 13:09:59 DEBUG] [actions:55] Filtering nodes by label kubernetes.io/hostname=minikube

[2022-06-10 13:09:59 DEBUG] [actions:57] Found 1 nodes

[2022-06-10 13:09:59 DEBUG] [actions:91] Picked nodes 'minikube'

[2022-06-10 13:09:59 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/home/interns_chaos/.kube/config'

[2022-06-10 13:09:59 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/home/interns_chaos/.kube/config'

[2022-06-10 13:09:59 DEBUG] [actions:51] Filtering nodes by name minikube

[2022-06-10 13:09:59 DEBUG] [actions:53] Found 1 nodes

[2022-06-10 13:09:59 DEBUG] [actions:91] Picked nodes 'minikube'

[2022-06-10 13:09:59 DEBUG] [actions:283] Found 16 pods on node 'minikube'

[2022-06-10 13:09:59 DEBUG] [activity:260] Activity failed

    Traceback (most recent call last):

      File "/home/interns_chaos/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity

        return func(**arguments)

      File "/home/interns_chaos/.local/lib/python3.8/site-packages/chaosk8s/node/actions.py", line 319, in drain_nodes

        for owner in pod.metadata.owner_references:

    TypeError: 'NoneType' object is not iterable

    

    During handling of the above exception, another exception occurred:

    

    Traceback (most recent call last):

      File "/home/interns_chaos/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 253, in run_activity

        result = run_python_activity(activity, configuration, secrets)

      File "/home/interns_chaos/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity

        raise ActivityFailed(

      File "/home/interns_chaos/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity

        return func(**arguments)

      File "/home/interns_chaos/.local/lib/python3.8/site-packages/chaosk8s/node/actions.py", line 319, in drain_nodes

        for owner in pod.metadata.owner_references:

    chaoslib.exceptions.ActivityFailed: TypeError: 'NoneType' object is not iterable

[2022-06-10 13:09:59 ERROR] [activity:213]   => failed: TypeError: 'NoneType' object is not iterable

[2022-06-10 13:09:59 INFO] [activity:223] Pausing after activity for 1s...

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'activity'

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'method'

[2022-06-10 13:10:00 DEBUG] [run:536] Running steady-state hypothesis after the method

[2022-06-10 13:10:00 INFO] [hypothesis:182] Steady state hypothesis: Nodes are indestructible

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'hypothesis'

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'activity'

[2022-06-10 13:10:00 INFO] [activity:188] Probe: all-apps-are-healthy

[2022-06-10 13:10:00 DEBUG] [python:33] Activity 'all-apps-are-healthy' loaded from '/home/interns_chaos/.local/lib/python3.8/site-packages/chaosk8s/probes.py'

[2022-06-10 13:10:00 WARNING] [__init__:165] all_microservices_healthy function is DEPRECATED and will be removed in the next         releases, please use all_pods_healthy instead

[2022-06-10 13:10:00 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/home/interns_chaos/.kube/config'

[2022-06-10 13:10:00 DEBUG] [probes:295] Found 0 failed and 0 not ready pods

[2022-06-10 13:10:00 DEBUG] [activity:205]   => succeeded with 'True'

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'activity'

[2022-06-10 13:10:00 DEBUG] [hypothesis:221] allowed tolerance is True

[2022-06-10 13:10:00 INFO] [hypothesis:231] Steady state hypothesis is met!

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'hypothesis'

[2022-06-10 13:10:00 WARNING] [run:641] Rollbacks were explicitly requested to be played

[2022-06-10 13:10:00 INFO] [run:893] Let's rollback...

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'rollback'

[2022-06-10 13:10:00 INFO] [rollback:27] No declared rollbacks, let's move on.

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'rollback'

[2022-06-10 13:10:00 INFO] [run:458] Experiment ended with status: completed

[2022-06-10 13:10:00 DEBUG] [__init__:399] No controls to apply on 'experiment'

[2022-06-10 13:10:00 DEBUG] [__init__:91] Cleaning up controls

[2022-06-10 13:10:00 DEBUG] [caching:42] Clearing activities cache

_Originally posted by @srimanth-h in https://github.com/chaostoolkit/chaostoolkit/discussions/264_

**Comment by srimanth-h** [comment]
hi, please can someone help me ?

**Comment by srimanth-h** [comment]
Hi, can someone please look into this issue ?
