### ISSUE TITLE
PDF report are getting crashed

### ISSUE THREAD

**Issue by ksraja00** [chaostoolkit/chaostoolkit#312]
Traceback (most recent call last):
  File "/usr/local/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/chaosreport/cli.py", line 95, in report
    save_report(header, reports, report_path, export_format)
  File "/usr/local/lib/python3.9/site-packages/chaosreport/__init__.py", line 313, in save_report
    major, minor, _ = pandoc_version.split(".", 2)

**Comment by Lawouach** [comment]
Thanks. This was fixed by @cdsre and I'm working on cutting a new release.

**Comment by ksraja00** [comment]
Thanks @cdsre.
@Lawouach pls let me know once deployed

**Comment by Lawouach** [comment]
Sure thing. It's under 0.18.0 now and available in the latest container image for the plugin.

Notice that, unfortunately, it now requires Python 3.10 because one of the dependency has such a constraint.

**Comment by ksraja00** [comment]
@Lawouach when shall the new changes will be deploy

**Comment by ksraja00** [comment]
@Lawouach @cdsre for time being, I installed the older pypandoc binaries and now able to generate report.

pip3 install pypandoc-binary==1.13
